spring.application.name=minio-service
minio.url=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucket=tiles
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
